[2023-05-02T14:37:00.368+0000] {processor.py:153} INFO - Started process (PID=58271) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:37:00.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:37:00.375+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:37:00.375+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:37:00.804+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:37:00.804+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:37:30.396+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:37:30.384+0000] {timeout.py:68} ERROR - Process timed out, PID: 58271
[2023-05-02T14:37:30.444+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:37:30.405+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58271
[2023-05-02T14:37:30.450+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:37:30.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.155 seconds
[2023-05-02T14:38:01.157+0000] {processor.py:153} INFO - Started process (PID=58291) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:38:01.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:38:01.179+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:38:01.179+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:38:01.585+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:38:01.585+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:38:31.226+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:38:31.220+0000] {timeout.py:68} ERROR - Process timed out, PID: 58291
[2023-05-02T14:38:31.242+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:38:31.231+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58291
[2023-05-02T14:38:31.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:38:31.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.138 seconds
[2023-05-02T14:39:01.775+0000] {processor.py:153} INFO - Started process (PID=58312) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:39:01.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:39:01.780+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:39:01.780+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:39:02.079+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:39:02.079+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:39:31.810+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:39:31.801+0000] {timeout.py:68} ERROR - Process timed out, PID: 58312
[2023-05-02T14:39:31.828+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:39:31.819+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58312
[2023-05-02T14:39:31.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:39:31.888+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.117 seconds
[2023-05-02T14:40:02.557+0000] {processor.py:153} INFO - Started process (PID=58332) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:40:02.560+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:40:02.562+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:40:02.562+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:40:03.193+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:40:03.193+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:40:32.584+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:40:32.572+0000] {timeout.py:68} ERROR - Process timed out, PID: 58332
[2023-05-02T14:40:32.630+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:40:32.593+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58332
[2023-05-02T14:40:32.635+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:40:32.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.146 seconds
[2023-05-02T14:41:03.316+0000] {processor.py:153} INFO - Started process (PID=58352) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:41:03.319+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:41:03.323+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:41:03.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:41:03.811+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:41:03.811+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:41:33.339+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:41:33.328+0000] {timeout.py:68} ERROR - Process timed out, PID: 58352
[2023-05-02T14:41:33.392+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:41:33.351+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58352
[2023-05-02T14:41:33.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:41:33.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.143 seconds
[2023-05-02T14:42:03.991+0000] {processor.py:153} INFO - Started process (PID=58371) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:42:03.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:42:03.998+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:42:03.998+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:42:04.473+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:42:04.472+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:42:34.022+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:42:34.012+0000] {timeout.py:68} ERROR - Process timed out, PID: 58371
[2023-05-02T14:42:34.044+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:42:34.032+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58371
[2023-05-02T14:42:34.047+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:42:34.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.133 seconds
[2023-05-02T14:43:04.737+0000] {processor.py:153} INFO - Started process (PID=58391) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:43:04.740+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:43:04.751+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:43:04.749+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:43:05.274+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:43:05.274+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:43:34.801+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:43:34.769+0000] {timeout.py:68} ERROR - Process timed out, PID: 58391
[2023-05-02T14:43:34.835+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:43:34.817+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58391
[2023-05-02T14:43:34.839+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:43:34.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.157 seconds
[2023-05-02T14:44:05.470+0000] {processor.py:153} INFO - Started process (PID=58412) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:44:05.475+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:44:05.479+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:44:05.478+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:44:06.009+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:44:06.009+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:44:35.498+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:44:35.490+0000] {timeout.py:68} ERROR - Process timed out, PID: 58412
[2023-05-02T14:44:35.524+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:44:35.509+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58412
[2023-05-02T14:44:35.536+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:44:35.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.149 seconds
[2023-05-02T14:45:06.153+0000] {processor.py:153} INFO - Started process (PID=58432) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:45:06.155+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:45:06.156+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:45:06.156+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:45:06.403+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:45:06.403+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:45:36.179+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:45:36.167+0000] {timeout.py:68} ERROR - Process timed out, PID: 58432
[2023-05-02T14:45:36.242+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:45:36.219+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58432
[2023-05-02T14:45:36.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:45:36.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.172 seconds
[2023-05-02T14:46:06.967+0000] {processor.py:153} INFO - Started process (PID=58453) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:46:06.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:46:06.974+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:46:06.973+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:46:07.313+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:46:07.312+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:46:36.986+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:46:36.982+0000] {timeout.py:68} ERROR - Process timed out, PID: 58453
[2023-05-02T14:46:37.008+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:46:36.991+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58453
[2023-05-02T14:46:37.012+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:46:37.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.124 seconds
[2023-05-02T14:47:07.495+0000] {processor.py:153} INFO - Started process (PID=58474) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:47:07.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:47:07.498+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:47:07.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:47:07.960+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:47:07.960+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:47:37.517+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:47:37.508+0000] {timeout.py:68} ERROR - Process timed out, PID: 58474
[2023-05-02T14:47:37.547+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:47:37.528+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58474
[2023-05-02T14:47:37.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:47:37.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.139 seconds
[2023-05-02T14:48:08.576+0000] {processor.py:153} INFO - Started process (PID=58493) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:48:08.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:48:08.586+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:48:08.585+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:48:09.104+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:48:09.104+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:48:38.616+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:48:38.602+0000] {timeout.py:68} ERROR - Process timed out, PID: 58493
[2023-05-02T14:48:38.662+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:48:38.638+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58493
[2023-05-02T14:48:38.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:48:38.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.172 seconds
[2023-05-02T14:49:09.147+0000] {processor.py:153} INFO - Started process (PID=58512) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:49:09.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:49:09.151+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:49:09.151+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:49:09.517+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:49:09.517+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:49:39.178+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:49:39.167+0000] {timeout.py:68} ERROR - Process timed out, PID: 58512
[2023-05-02T14:49:39.206+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:49:39.191+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58512
[2023-05-02T14:49:39.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:49:39.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.131 seconds
[2023-05-02T14:50:09.993+0000] {processor.py:153} INFO - Started process (PID=58531) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:50:09.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:50:10.001+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:50:10.001+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:50:10.843+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:50:10.843+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:50:40.031+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:50:40.017+0000] {timeout.py:68} ERROR - Process timed out, PID: 58531
[2023-05-02T14:50:40.097+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:50:40.046+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58531
[2023-05-02T14:50:40.101+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:50:40.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.189 seconds
[2023-05-02T14:51:10.686+0000] {processor.py:153} INFO - Started process (PID=58552) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:51:10.690+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:51:10.692+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:51:10.691+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:51:11.065+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:51:11.064+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:51:40.723+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:51:40.714+0000] {timeout.py:68} ERROR - Process timed out, PID: 58552
[2023-05-02T14:51:40.780+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:51:40.735+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58552
[2023-05-02T14:51:40.790+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:51:40.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.168 seconds
[2023-05-02T14:52:11.311+0000] {processor.py:153} INFO - Started process (PID=58572) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:52:11.314+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:52:11.316+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:52:11.316+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:52:11.587+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:52:11.587+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:52:41.348+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:52:41.327+0000] {timeout.py:68} ERROR - Process timed out, PID: 58572
[2023-05-02T14:52:42.509+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:52:41.830+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58572
[2023-05-02T14:52:42.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:52:42.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 31.549 seconds
[2023-05-02T14:53:13.759+0000] {processor.py:153} INFO - Started process (PID=58592) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:53:13.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:53:13.764+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:53:13.763+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:53:14.217+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:53:14.216+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:53:43.786+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:53:43.773+0000] {timeout.py:68} ERROR - Process timed out, PID: 58592
[2023-05-02T14:53:43.847+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:53:43.824+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58592
[2023-05-02T14:53:43.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:53:43.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.159 seconds
[2023-05-02T14:54:14.445+0000] {processor.py:153} INFO - Started process (PID=58613) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:54:14.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:54:14.450+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:54:14.450+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:54:14.881+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:54:14.881+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:54:44.467+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:54:44.459+0000] {timeout.py:68} ERROR - Process timed out, PID: 58613
[2023-05-02T14:54:44.491+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:54:44.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58613
[2023-05-02T14:54:44.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:54:44.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.096 seconds
[2023-05-02T14:55:15.094+0000] {processor.py:153} INFO - Started process (PID=58633) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:55:15.096+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:55:15.098+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:55:15.098+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:55:16.122+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:55:16.121+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:55:45.118+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:55:45.107+0000] {timeout.py:68} ERROR - Process timed out, PID: 58633
[2023-05-02T14:55:45.148+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:55:45.127+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58633
[2023-05-02T14:55:45.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:55:45.205+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.116 seconds
[2023-05-02T14:56:15.636+0000] {processor.py:153} INFO - Started process (PID=58652) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:56:15.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:56:15.642+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:56:15.642+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:56:16.069+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:56:16.068+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
[2023-05-02T14:56:45.677+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:56:45.665+0000] {timeout.py:68} ERROR - Process timed out, PID: 58652
[2023-05-02T14:56:45.708+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:56:45.684+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_bualuang_historical_funds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 61, in <module>
    default_args=default_args)
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 20, in __init__
    self.create_task()
  File "/opt/airflow/dags/dag_bualuang_historical_funds.py", line 30, in create_task
    task1_result = task1.execute(None)
  File "/opt/airflow/plugins/selenium_plugin/operators/selenium_operator.py", line 38, in execute
    command_executor=self.remote_url, desired_capabilities=self.browser_capabilities
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_bualuang_historical_funds.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.3/best-practices.html#reducing-dag-complexity, PID: 58652
[2023-05-02T14:56:45.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:56:45.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_bualuang_historical_funds.py took 30.174 seconds
[2023-05-02T14:57:16.264+0000] {processor.py:153} INFO - Started process (PID=58672) to work on /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:57:16.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_bualuang_historical_funds.py for tasks to queue
[2023-05-02T14:57:16.268+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:57:16.267+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_bualuang_historical_funds.py
[2023-05-02T14:57:16.657+0000] {logging_mixin.py:137} INFO - [2023-05-02T14:57:16.657+0000] {selenium_operator.py:36} INFO - Initializing Selenium WebDriver
